// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Dynamic_Island

#ifndef _DYNAMIC_ISLAND_UI_H
#define _DYNAMIC_ISLAND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void IslandWider_Animation(lv_obj_t * TargetObject, int delay);
void IslandBigger_Animation(lv_obj_t * TargetObject, int delay);
void ImageGoLeft_Animation(lv_obj_t * TargetObject, int delay);
void ImageGoRight_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScreenIslandDemo
void ui_ScreenIslandDemo_screen_init(void);
extern lv_obj_t * ui_ScreenIslandDemo;
extern lv_obj_t * ui_Island;
extern lv_obj_t * ui_ImageChargingLabel;
extern lv_obj_t * ui_ImageBattery;
extern lv_obj_t * ui_IslandMask;
void ui_event_ButtonWider(lv_event_t * e);
extern lv_obj_t * ui_ButtonWider;
extern lv_obj_t * ui_LabelWider;
void ui_event_ButtonBigger(lv_event_t * e);
extern lv_obj_t * ui_ButtonBigger;
extern lv_obj_t * ui_LabelBigger;
void ui_event_ButtonCharging(lv_event_t * e);
extern lv_obj_t * ui_ButtonCharging;
extern lv_obj_t * ui_LabelCharging;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_charging_png);    // assets/charging.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
